import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT=path.resolve('public');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const srv=http.createServer((req,resp)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/')p='/index.html';const fp=path.join(ROOT,p);if(!fp.startsWith(ROOT)||!fs.existsSync(fp)){resp.writeHead(404);return resp.end('nf');}resp.writeHead(200,{'content-type':MIME[path.extname(fp)]||'application/octet-stream'});fs.createReadStream(fp).pipe(resp);});
await new Promise(r=>srv.listen(8790,'127.0.0.1',r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const pg=await b.newPage();
const failed=[];
pg.on('requestfailed',r=>failed.push([r.url(),r.failure()?.errorText]));
pg.on('response',r=>{if(r.status()>=400)failed.push([r.url(),r.status()]);});
await pg.goto('http://127.0.0.1:8790/',{waitUntil:'networkidle',timeout:60000}).catch(()=>{});
await pg.waitForTimeout(1500);
console.log(JSON.stringify(failed,null,1));
await b.close();srv.close();
